version: '3.9'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    container_name: clickhouse
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9003
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - 8123:8123
      - 9003:9003
    volumes:
      - clickhouse-data:/bitnami/clickhouse
      - clickhouse-backup:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml
    networks:
      - deepfind

  chroma:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chroma
    volumes:
      - chroma:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8100 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - 8100:8100
    depends_on:
      - clickhouse
    networks:
      - deepfind

networks:
  deepfind:
    name: deepfind
    driver: bridge

volumes:
  chroma:
    name: 'chroma'
  clickhouse-data:
    name: 'clickhouse-data'
  clickhouse-backup:
    name: 'clickhouse-backup'
